language: go

env:
  - GO111MODULE=on

go:
  - 1.12.x

services:
  - docker

before_install:
  - ./docker-start.sh

script:
  - ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)